# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9900617842ce5b09b0637963ccb7c4ef41d25172a0d79a9c3fc1282cc1b90295f88876e17623fd4222c9ebb67c35d0826a9194c739edc14f8111213d0e9e13

test:
  secret_key_base: c40c8c12fc7fe45f8932d6045a3f4ce96c8e78ac042d42d6786b06b0841e53964ce9ddb2cc2124cf03dc3bf17bcbc621cb60580f2d976d28bc5ce3fea0b9fa81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
